CREATE TABLE IF NOT EXISTS `surfacetypes` (
  `SurfaceType` varchar(3) NOT NULL,
  `Description` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`SurfaceType`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

INSERT INTO `surfacetypes` (`SurfaceType`, `Description`) VALUES
('ASP', 'ASPHALT, ASPHALTIC CONCRETE, TAR MACADAM, OR BITUMEN BOUND MACADAM (INCLUDING ANY OF THESE SURFACE TYPES WITH CONCRETE ENDS).'),
('BIT', 'BITUMINOUS, TAR OR ASPHALT MIXED IN PLACE, OILED.'),
('BRI', 'BRICK, LAID OR MORTARED.'),
('CLA', 'CLAY.'),
('COM', 'COMPOSITE, LESS THAN 50 PERCENT OF THE RUNWAY LENGTH IS PERMANENT.'),
('CON', 'CONCRETE.'),
('COP', 'COMPOSITE, 50 PERCENT OR MORE OF THE RUNWAY LENGTH IS PERMANENT.'),
('COR', 'CORAL.'),
('GRE', 'GRADED OR ROLLED EARTH, GRASS ON GRADED EARTH.'),
('GRS', 'GRASS OR EARTH NOT GRADED OR GRASS OR EARTH NOT GRADED OR ROLLED.'),
('GVL', 'GRAVEL.'),
('ICE', 'ICE.'),
('LAT', 'LATERITE.'),
('MAC', 'MACADAM - CRUSHED ROCK WATER BOUND.'),
('MEM', 'MEMBRANE - PLASTIC OR OTHER COATED FIBER MATERIAL.'),
('MIX', 'MIX IN PLACE USING NONBITUMIOUS BINDERS SUCH AS PORTLAND CEMENT.'),
('PEM', 'PART CONCRETE, PART ASPHALT, OR PART BITUMEN-BOUND MACADAM.'),
('PER', 'PERMANENT, SURFACE TYPE UNKNOWN.'),
('PSP', 'PIECED STEEL PLANKING.'),
('SAN', 'SAND, GRADED, ROLLED OR OILED.'),
('SNO', 'SNOW.'),
('U', 'SURFACE UNKNOWN.'),
('WAT', 'WATER');